name: speckit-upload-logs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  actions: write

jobs:
  upload:
    name: Sanitize and upload run logs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect run logs
        id: detect
        run: |
          if [ -d runs ]; then
            count=$(find runs -type f | wc -l | tr -d ' ')
          else
            count=0
          fi

          if [ "$count" -gt 0 ]; then
            printf 'has_logs=true\n' >> "$GITHUB_OUTPUT"
          else
            printf 'has_logs=false\n' >> "$GITHUB_OUTPUT"
          fi

          printf 'log_count=%s\n' "$count" >> "$GITHUB_OUTPUT"
          echo "speckit-upload-logs: detected ${count} run file(s)."

      - name: Sanitize logs
        if: steps.detect.outputs.has_logs == 'true'
        id: sanitize
        run: |
          node <<'NODE'
          const fs = require('fs');
          const path = require('path');
          const patternsPath = path.join(process.cwd(), 'packages', 'speckit-core', 'patterns', 'sanitizer-patterns.json');
          const definitions = JSON.parse(fs.readFileSync(patternsPath, 'utf8'));
          const patterns = definitions.map(def => {
            const flags = def.flags ? (def.flags.includes('g') ? def.flags : `${def.flags}g`) : 'g';
            return {
              pattern: def.pattern,
              regex: new RegExp(def.pattern, flags),
              replacement: def.replacement,
            };
          });
          const root = process.cwd();
          const sourceDir = path.join(root, 'runs');
          const destDir = path.join(root, 'sanitized-logs');
          let hits = 0;
          const patternHits = new Map();

          function sanitizeText(text) {
            let next = text;
            for (const pattern of patterns) {
              pattern.regex.lastIndex = 0;
              const matches = next.match(pattern.regex);
              if (!matches || matches.length === 0) {
                continue;
              }
              hits += matches.length;
              patternHits.set(pattern.pattern, (patternHits.get(pattern.pattern) ?? 0) + matches.length);
              pattern.regex.lastIndex = 0;
              next = next.replace(pattern.regex, pattern.replacement);
              pattern.regex.lastIndex = 0;
            }
            return next;
          }

          function walk(dir) {
            for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
              const full = path.join(dir, entry.name);
              const relative = path.relative(sourceDir, full);
              const target = path.join(destDir, relative);
              if (entry.isDirectory()) {
                fs.mkdirSync(target, { recursive: true });
                walk(full);
              } else if (entry.isFile()) {
                const original = fs.readFileSync(full, 'utf8');
                const sanitized = sanitizeText(original);
                fs.mkdirSync(path.dirname(target), { recursive: true });
                fs.writeFileSync(target, sanitized, 'utf8');
              }
            }
          }

          if (!fs.existsSync(sourceDir)) {
            console.error('runs/ directory disappeared before sanitizing.');
            process.exit(1);
          }

          fs.mkdirSync(destDir, { recursive: true });
          walk(sourceDir);
          fs.writeFileSync(
            path.join(destDir, 'sanitizer-report.json'),
            JSON.stringify(
              {
                hits,
                pattern_hits: Object.fromEntries(patternHits.entries()),
              },
              null,
              2
            )
          );
          console.log(`Sanitized logs with ${hits} potential secret hits.`);
          NODE

      - name: Create archive
        if: steps.detect.outputs.has_logs == 'true'
        run: |
          tar -czf agent-run-logs.tar.gz -C sanitized-logs .

      - name: Upload sanitized logs
        if: steps.detect.outputs.has_logs == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: agent-run-logs
          path: agent-run-logs.tar.gz

      - name: No logs warning
        if: steps.detect.outputs.has_logs != 'true'
        env:
          LOG_COUNT: ${{ steps.detect.outputs.log_count }}
        run: |
          count="${LOG_COUNT:-0}"
          echo "speckit-upload-logs: no runs/ logs found (detected ${count} file(s)). Upload skipped."
